# config.ini — конфигурация эмулятора PCE Mac Plus
# Синтаксис: libini (PCE) — секции через { }, комментарии через #

system {
	model = "mac-plus"
}

cpu {
	model = "68000"
	speed = 0
}

ram {
	address = 0x000000
	size    = 128K
	default = 0x00
}

rom {
	address = 0x400000
	size    = 65536
	file    = "mac-128k.rom"
	default = 0xff
}

keyboard {
	model         = 1
	intl          = 0
	keypad_motion = 0
}

sony {
	enable       = 1
	insert_delay = 1
}

disk {
	drive    = 1
	type     = "auto"
	file     = "system.img"
	optional = 0
}

video {
	width  = 512
	height = 342
}

sound {
	lowpass = 6000
	driver  = "null"
}

terminal {
	driver = "null"
}
